services:
  manager_1:
    build:
      context: .
      dockerfile: ./infra_management/Dockerfile
    container_name: manager_1
    environment:
      - MANAGER_ID=1
    volumes:
      - ./infra_management/config.yaml:/app/config.yaml
      - ./architecture.yaml:/app/architecture.yaml
      - /var/run/docker.sock:/var/run/docker.sock
  manager_2:
    build:
      context: .
      dockerfile: ./infra_management/Dockerfile
    container_name: manager_2
    environment:
      - MANAGER_ID=2
    volumes:
      - ./infra_management/config.yaml:/app/config.yaml
      - ./architecture.yaml:/app/architecture.yaml
      - /var/run/docker.sock:/var/run/docker.sock
  manager_3:
    build:
      context: .
      dockerfile: ./infra_management/Dockerfile
    container_name: manager_3
    environment:
      - MANAGER_ID=3
    volumes:
      - ./infra_management/config.yaml:/app/config.yaml
      - ./architecture.yaml:/app/architecture.yaml
      - /var/run/docker.sock:/var/run/docker.sock
  manager_4:
    build:
      context: .
      dockerfile: ./infra_management/Dockerfile
    container_name: manager_4
    environment:
      - MANAGER_ID=4
    volumes:
      - ./infra_management/config.yaml:/app/config.yaml
      - ./architecture.yaml:/app/architecture.yaml
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  rabbitmq_data:
