services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Admin interface
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./datasets:/app/datasets

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
