services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Admin interface
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 10s
      retries: 5

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    volumes:
      - ./datasets:/app/datasets

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "12345:12345"
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  rabbitmq_data:
