client:
    container_name: client_{{CLIENT_ID}}
    build:
      context: .
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    volumes:
      - ./datasets:/app/datasets
      - ./client/config.yaml:/app/config.yaml
      - ./results/client_{{CLIENT_ID}}:/app/results