server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "12345:12345"
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
    volumes:
      - ./server/config.yaml:/app/config.yaml
      - ./architecture.yaml:/app/architecture.yaml