worker:
  container_name: node_<<NODE_ID>>
  build:
    context: .
    dockerfile: ./worker/Dockerfile
  depends_on:
    rabbitmq:
      condition: service_healthy
  links:
    - rabbitmq
  volumes:
    - ./architecture.yaml:/app/architecture.yaml
    - ./worker/common.yaml:/app/common.yaml
    - ./configs/controller_node_<<NODE_ID>>.yaml:/app/controllers.yaml
    - ./worker_files/node_<<NODE_ID>>/data:/app/data
    - ./worker_files/node_<<NODE_ID>>/metadata:/app/metadata
