controllers:
  bufferSize:
    toSend: 50
    deadHandlers: 20

queries:
  1:
     

use:
  - type: MAP_FILTER_GAMES
    queries:
      - Q1
      - Q2
      - Q3
      - Q4
      - Q5
    
  - type: Q1_STAGE_3
    partition:
      before: 10
      after: 1
  
  - type: Q2_STAGE_2
    partition:
      size: 3
